---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
upload_dir: uploads
public_path: https://res.cloudinary.com/satellitedashboard/image/upload
front_matter_path: https://res.cloudinary.com/satellitedashboard/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: ".nuxt"
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
