/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:82bf7636-b88f-4bf4-8f80-30727201e05c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NFJLmTshh",
    "aws_user_pools_web_client_id": "4pnmd865verd8tmpgbkhc1d859",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://kew22ds5rvbefappmskraq2j6y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tmhdcre5pfh3jf5ej73xyzfrxy",
    "aws_user_files_s3_bucket": "satellitedashboardf04cb9ea85d14e1d9b04cee1193d1202425-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
