name: Access AstriaGraph

on:
  schedule:
    - cron: "*/60 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Webhook
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.AG_API_URL }}
